/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author gguzm
 */
public class ConversorGenerico extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public ConversorGenerico() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Conversor");
        // TODO Investigar como hacer para qué la ventana no se puede redimensionar
        
        
        ///////////////////////////////////////////////
        conversores = new ArrayList<Conversor>();
        conversores.add(new ConversorCentPulg());
        conversores.add(new ConversorMetroKM());
        // TODO agregar 3 Conversores más
        
        
        for (Conversor conversor : conversores) {
            jComboBoxConversores.addItem(conversor.getTipo());
        }
        
        setConversorSelccionado();
    }

    private void setConversorSelccionado() {
        int selectedIndex = jComboBoxConversores.getSelectedIndex();
        conversorSeleccionado = conversores.get(selectedIndex);
        jLabel1.setText(conversorSeleccionado.getLabel1());
        // TODO
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPulg = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jComboBoxConversores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Label 1");

        jTextFieldUno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUnoFocusLost(evt);
            }
        });
        jTextFieldUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUnoKeyPressed(evt);
            }
        });

        jLabel2.setText("Label 2");

        jTextFieldPulg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPulgFocusLost(evt);
            }
        });

        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jComboBoxConversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConversoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldPulg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxConversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldUno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConvertir)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxConversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jButtonConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPulg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUnoFocusLost
        convertirAValorDos = true;        
    }//GEN-LAST:event_jTextFieldUnoFocusLost

    private void jTextFieldPulgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPulgFocusLost
        convertirAValorDos = false;
    }//GEN-LAST:event_jTextFieldPulgFocusLost

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        if (convertirAValorDos) {
            convertirAValorDos();
        }
        else {
            // TODO
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void convertirAValorDos() {
        Double valorUno;
        try {
            // TODO ',' o '.' son los separadores de decimales
            // String text = jTextFieldCent.getText();
            valorUno = Double.valueOf(jTextFieldUno.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al convertir "+conversorSeleccionado.getLabel1()+" a "+conversorSeleccionado.getLabel2(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double valorDos = conversorSeleccionado.convertirValorUnoValorDos(valorUno);
        jTextFieldPulg.setText(String.format("%.2f", valorDos));
    }

    private void jTextFieldUnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUnoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            convertirAValorDos();
        }
    }//GEN-LAST:event_jTextFieldUnoKeyPressed

    private void jComboBoxConversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConversoresActionPerformed
        setConversorSelccionado();
    }//GEN-LAST:event_jComboBoxConversoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JComboBox<String> jComboBoxConversores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldPulg;
    private javax.swing.JTextField jTextFieldUno;
    // End of variables declaration//GEN-END:variables
    private boolean convertirAValorDos;
    private List<Conversor> conversores;
    private Conversor conversorSeleccionado;
}
