/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author g.guzman
 */
public class Conversor extends javax.swing.JFrame {
    
    private AbstractConversor conversorSeleccionado;
    private final List<AbstractConversor> conversores;

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mi Conversor");
        
        conversores = new ArrayList<>();
        conversores.add(new MetrosKmConversor());
        conversores.add(new CentPulgConversor());
        // TODO Agregar más conversores
        
        for (AbstractConversor conversor : conversores) {
            conversoresComboBox.addItem(conversor.getNombre());
        }
        
        //conversorSeleccionado = new CentPulgConversor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor1TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        convertirAPulgadasButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        valor2TextField = new javax.swing.JTextField();
        convertirACentiometrosButton = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        conversoresComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valor1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valor1TextFieldFocusLost(evt);
            }
        });
        valor1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1TextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Label1:");

        convertirAPulgadasButton.setText("A pulgadas");
        convertirAPulgadasButton.setEnabled(false);
        convertirAPulgadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirAPulgadasButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Label2:");

        valor2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valor2TextFieldFocusLost(evt);
            }
        });
        valor2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2TextFieldActionPerformed(evt);
            }
        });
        valor2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valor2TextFieldKeyPressed(evt);
            }
        });

        convertirACentiometrosButton.setText("A centímetros");
        convertirACentiometrosButton.setEnabled(false);
        convertirACentiometrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirACentiometrosButtonActionPerformed(evt);
            }
        });

        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        conversoresComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversoresComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Conversor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(conversoresComboBox, 0, 116, Short.MAX_VALUE)
                            .addComponent(valor1TextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertirAPulgadasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirACentiometrosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convertirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(convertirAPulgadasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(convertirACentiometrosButton))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1TextFieldActionPerformed

    private void valor2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2TextFieldActionPerformed

    private void convertirAPulgadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirAPulgadasButtonActionPerformed
        System.out.println("convertirAPulgadasButtonActionPerformed");
        String centimetros = valor1TextField.getText().replace(',', '.');
        
        Double centDouble;
        try {
            centDouble = Double.valueOf(centimetros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al convertir", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double pulgDouble = centDouble ;
        
        //pulgadasTextField.setText(String.valueOf(pulgDouble));
        valor2TextField.setText(String.format("%.2f", pulgDouble));
    }//GEN-LAST:event_convertirAPulgadasButtonActionPerformed

    private void convertirACentiometrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirACentiometrosButtonActionPerformed
        System.out.println("convertirACentimetrosButtonActionPerformed");
        convertirAValor1();
    }//GEN-LAST:event_convertirACentiometrosButtonActionPerformed

    private void convertirAValor1() throws HeadlessException {
        String pulgadas = valor2TextField.getText().replace(',', '.'); // Obtenemos el texto de pulgadas
        Double pulgDouble;
        try {
            String pulgadasLower = pulgadas.toLowerCase();
            if (pulgadasLower.contains("f") || pulgadasLower.contains("d")) {
                throw new NumberFormatException("El valor contiene una 'f' o una 'd'");
            }
            pulgDouble = Double.valueOf(pulgadas);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir ("+ex.getLocalizedMessage()+")", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Multiplicamos por 2.54 para pasar de pulgadas a centímetros
        double centimetros = conversorSeleccionado.convertirAValor1(pulgDouble);
        // Mostramos el resultado en el campo de texto de centímetros
        valor1TextField.setText(String.format("%.2f", centimetros));
    }

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        if (convertirAValor2) {
            // TODO
        }
        else {
            convertirAValor1();
        }
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void valor1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor1TextFieldFocusLost
        convertirAValor2 = true;
    }//GEN-LAST:event_valor1TextFieldFocusLost

    private void valor2TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor2TextFieldFocusLost
        convertirAValor2 = false;
    }//GEN-LAST:event_valor2TextFieldFocusLost

    private void conversoresComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversoresComboBoxActionPerformed
        int selectedIndex = conversoresComboBox.getSelectedIndex();
        conversorSeleccionado = conversores.get(selectedIndex);

        jLabel1.setText(conversorSeleccionado.getLabel1());
        jLabel2.setText(conversorSeleccionado.getLabel2());

    }//GEN-LAST:event_conversoresComboBoxActionPerformed

    private void valor2TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor2TextFieldKeyPressed
        if (evt.getKeyChar()==KeyEvent.VK_ENTER) {
            convertirAValor1();
        }
    }//GEN-LAST:event_valor2TextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

//    private static final double UNA_PULGADA = 2.54;
    private boolean convertirAValor2;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conversoresComboBox;
    private javax.swing.JButton convertirACentiometrosButton;
    private javax.swing.JButton convertirAPulgadasButton;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField valor1TextField;
    private javax.swing.JTextField valor2TextField;
    // End of variables declaration//GEN-END:variables
}
