/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversorgenerico;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author g.guzman
 */
public class ConversorGUI extends javax.swing.JFrame {

    private static final Double UNA_PULGADA = 2.54;
    private AbstractConversor conversorSeleccionado;
    private List<AbstractConversor> conversores;

    /**
     * Creates new form ConversorGUI
     */
    public ConversorGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        conversores = new ArrayList<>();
        conversores.add(new CentimetroPulgadaConversor());
        conversores.add(new MetroKmConversor());
        conversores.add(new PesoRealConversor());
        // TODO: agragar mas tipos de conversores
        
        
        for (AbstractConversor conversor : conversores) {
            conversorComboBox.addItem(conversor.getNombreConversor());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        aPulgadasButton = new javax.swing.JButton();
        centimetrosTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pulgadasTextField = new javax.swing.JTextField();
        aCentimetrosButton = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        conversorComboBox = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aPulgadasButton.setText("A Pulgadas");
        aPulgadasButton.setEnabled(false);
        aPulgadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPulgadasButtonActionPerformed(evt);
            }
        });

        centimetrosTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                centimetrosTextFieldFocusLost(evt);
            }
        });
        centimetrosTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                centimetrosTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setText("Centímetros:");

        jLabel2.setText("Pulgadas:");

        pulgadasTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pulgadasTextFieldFocusLost(evt);
            }
        });
        pulgadasTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pulgadasTextFieldKeyPressed(evt);
            }
        });

        aCentimetrosButton.setText("A Centímetros");
        aCentimetrosButton.setEnabled(false);
        aCentimetrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCentimetrosButtonActionPerformed(evt);
            }
        });

        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        conversorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(centimetrosTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(convertirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(aCentimetrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(aPulgadasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(conversorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centimetrosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(aPulgadasButton))
                .addGap(7, 7, 7)
                .addComponent(convertirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aCentimetrosButton)
                    .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aPulgadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPulgadasButtonActionPerformed
        convertirAPulgadas();
    }//GEN-LAST:event_aPulgadasButtonActionPerformed

    private void convertirAPulgadas() throws HeadlessException {
        System.out.println("Presionó aPulgadasButtonActionPerformed !!");
        // Tomar el valor del Textfield Pulgadas
        String centText = centimetrosTextField.getText();
        centText = centText.replace(',', '.');
        Double centDouble;
        try {
            if (centText.contains("d") || centText.contains("D") ||
                    centText.toLowerCase().contains("f")) {
                throw new NumberFormatException();
            }
            centDouble = Double.valueOf(centText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo convertir el valor "+centText,
                    "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double pulgadasDouble = conversorSeleccionado.convertirValor1Valor2(centDouble);
        pulgadasTextField.setText(String.format("%.2f", pulgadasDouble));
        //pulgadasTextField.setText(String.format(Locale.ENGLISH, "%.2f", pulgadasDouble));
    }
    
    private void convertirACentimetros() throws HeadlessException {
        System.out.println("Presionó aPulgadasButtonActionPerformed !!");
        // Tomar el valor del Textfield Pulgadas
        String pulgText = pulgadasTextField.getText();
        pulgText = pulgText.replace(',', '.');
        Double pulgDouble;
        try {
            if (pulgText.contains("d") || pulgText.contains("D") ||
                    pulgText.toLowerCase().contains("f")) {
                throw new NumberFormatException();
            }
            pulgDouble = Double.valueOf(pulgText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo convertir el valor "+pulgText,
                    "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double centimetrosDouble = conversorSeleccionado.convertirValor2Valor1(pulgDouble);
        centimetrosTextField.setText(String.format("%.2f", centimetrosDouble));
        //pulgadasTextField.setText(String.format(Locale.ENGLISH, "%.2f", pulgadasDouble));
    }

    private void aCentimetrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCentimetrosButtonActionPerformed
        System.out.println("Presionó aPulgadasButtonActionPerformed !!");

        // Tomar el valor del Textfield Pulgadas
        String pulgText = pulgadasTextField.getText();
        pulgText = pulgText.replace(',', '.');
        Double pulgDouble;
        try {
            if (pulgText.contains("d") || pulgText.contains("D") ||
                pulgText.toLowerCase().contains("f")) {
                throw new NumberFormatException();
            }
            pulgDouble = Double.valueOf(pulgText);
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo convertir el valor "+pulgText,
                "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double centDouble = pulgDouble * UNA_PULGADA;

        centimetrosTextField.setText(String.format("%.2f", centDouble));
    }//GEN-LAST:event_aCentimetrosButtonActionPerformed

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        if (convertirAPulgadas) {
            convertirAPulgadas();
        }
        else {
            convertirACentimetros();
        }
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void centimetrosTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_centimetrosTextFieldFocusLost
        convertirAPulgadas = true;
    }//GEN-LAST:event_centimetrosTextFieldFocusLost

    private void pulgadasTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pulgadasTextFieldFocusLost
        convertirAPulgadas = false;
    }//GEN-LAST:event_pulgadasTextFieldFocusLost

    private void centimetrosTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centimetrosTextFieldKeyPressed
        if (evt.getKeyChar()==KeyEvent.VK_ENTER) {
            convertirAPulgadas();
        }
    }//GEN-LAST:event_centimetrosTextFieldKeyPressed

    private void conversorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversorComboBoxActionPerformed
        System.out.println("conversorgenerico.ConversorGUI.conversorComboBoxActionPerformed()");
        int selectedIndex = conversorComboBox.getSelectedIndex();
        conversorSeleccionado = conversores.get(selectedIndex);
        jLabel1.setText(conversorSeleccionado.getLabel1());
        jLabel2.setText(conversorSeleccionado.getLabel2());
    }//GEN-LAST:event_conversorComboBoxActionPerformed

    private void pulgadasTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pulgadasTextFieldKeyPressed
        if (evt.getKeyChar()==KeyEvent.VK_ENTER) {
            convertirACentimetros();
        }
    }//GEN-LAST:event_pulgadasTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGUI().setVisible(true);
            }
        });
    }

    private boolean convertirAPulgadas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCentimetrosButton;
    private javax.swing.JButton aPulgadasButton;
    private javax.swing.JTextField centimetrosTextField;
    private javax.swing.JComboBox<String> conversorComboBox;
    private javax.swing.JButton convertirButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pulgadasTextField;
    // End of variables declaration//GEN-END:variables
}
