/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversorgenerico;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author g.guzman
 */
public class ConversorGUI extends javax.swing.JFrame {
    private ConversorAbstracto conversorSeleccionado;
    List<ConversorAbstracto> conversores;

    /**
     * Creates new form ConversorGUI
     */
    public ConversorGUI() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Mi Conversor");
        
        conversores = new ArrayList<>();
        conversores.add(new CentPulgConversor());
        conversores.add(new MetroKMConversor());
        
        for (ConversorAbstracto conversor : conversores) {
            conversoresComboBox.addItem(conversor.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aPulgadasButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pulgTextField = new javax.swing.JTextField();
        aCentimetrosButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        conversoresComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        centTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                centTextFieldFocusLost(evt);
            }
        });
        centTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                centTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setText("label1:");

        aPulgadasButton.setText("a Pulgadas");
        aPulgadasButton.setEnabled(false);
        aPulgadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPulgadasButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("label2:");

        pulgTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pulgTextFieldFocusLost(evt);
            }
        });

        aCentimetrosButton.setText("a Centímetros");
        aCentimetrosButton.setEnabled(false);
        aCentimetrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCentimetrosButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        conversoresComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversoresComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Conversor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(conversoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(centTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pulgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aPulgadasButton)
                                    .addComponent(aCentimetrosButton))
                                .addGap(43, 43, 43))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetButton)
                    .addComponent(convertirButton))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(aPulgadasButton))
                .addGap(7, 7, 7)
                .addComponent(convertirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(aCentimetrosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aPulgadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPulgadasButtonActionPerformed
        convertirAValor2();
    }//GEN-LAST:event_aPulgadasButtonActionPerformed

    private void convertirAValor2() throws HeadlessException {
        //System.out.println("conversorgenerico.ConversorGUI.aPulgadasButtonActionPerformed()");
        String centStr = centTextField.getText().replace(',', '.');
        Double centDouble;
        try {
            if (centStr.toLowerCase().contains("d") || centStr.toLowerCase().contains("f")) {
                throw new NumberFormatException("El texto ingresado contiene un D o F");
            }
            centDouble = Double.valueOf(centStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error de conversión ("+ex.getLocalizedMessage()+")",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Double pulgDouble = centDouble / 2.54;
        Double pulgDouble = conversorSeleccionado.convertirValor1Valor2(centDouble);
        final String pulgStr = String.format("%.2f", pulgDouble);
        pulgTextField.setText(pulgStr);
    }

    private void aCentimetrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCentimetrosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aCentimetrosButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        resetFields();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void resetFields() {
        centTextField.setText("");
        pulgTextField.setText("");
    }

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        if (convertirAPulg) {
            convertirAValor2();
        }
        else {
            // TODO: convertir a centímetros
        }
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void centTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_centTextFieldFocusLost
        convertirAPulg = true;
    }//GEN-LAST:event_centTextFieldFocusLost

    private void pulgTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pulgTextFieldFocusLost
        convertirAPulg = false;
    }//GEN-LAST:event_pulgTextFieldFocusLost

    private void centTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centTextFieldKeyPressed
        if (evt.getKeyChar()==KeyEvent.VK_ENTER) {
            convertirAValor2();
        }
    }//GEN-LAST:event_centTextFieldKeyPressed

    private void conversoresComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversoresComboBoxActionPerformed
        int selctedIndex = conversoresComboBox.getSelectedIndex();
        conversorSeleccionado = conversores.get(selctedIndex);
        jLabel1.setText(conversorSeleccionado.getLabel1());
        jLabel2.setText(conversorSeleccionado.getLabel2());
        resetFields();
    }//GEN-LAST:event_conversoresComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCentimetrosButton;
    private javax.swing.JButton aPulgadasButton;
    private javax.swing.JTextField centTextField;
    private javax.swing.JComboBox<String> conversoresComboBox;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pulgTextField;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    private boolean convertirAPulg;
}
