/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversorgui;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author g.guzman
 */
public class ConversorGUI extends javax.swing.JFrame {

    private static final double UNA_PULGADA = 2.54;
    
    /**
     * Creates new form ConversorGUI
     */
    public ConversorGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mi Conversor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        centTextField = new javax.swing.JTextField();
        aPulgadasButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pulgTextField = new javax.swing.JTextField();
        aCentimetrosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Centímetros:");

        centTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                centTextFieldKeyPressed(evt);
            }
        });

        aPulgadasButton.setText("A Pulgadas");
        aPulgadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPulgadasButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Pulgadas:");

        aCentimetrosButton.setText("A Centímetros");
        aCentimetrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCentimetrosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pulgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(centTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aCentimetrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(aPulgadasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(centTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPulgadasButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pulgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aCentimetrosButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aCentimetrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCentimetrosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aCentimetrosButtonActionPerformed

    private void aPulgadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPulgadasButtonActionPerformed
        System.out.println("conversorgui.ConversorGUI.aPulgadasButtonActionPerformed()");
        convertirAPulgadas();
    }//GEN-LAST:event_aPulgadasButtonActionPerformed

    private void convertirAPulgadas() throws HeadlessException {
        // 1. Tomamos el valor del Textfield centímetros
        String centText = centTextField.getText().replace(',', '.');
        Double centDouble;
        try {
            if (centText.toLowerCase().contains("f") || centText.toLowerCase().contains("d")) {
                throw new NumberFormatException("Se ha ingresado una 'f' o una 'd'");
            }
            centDouble = Double.valueOf(centText);
        } catch (NumberFormatException e) {
            pulgTextField.setText("");
            JOptionPane.showMessageDialog(this, "No se pudo convertir ("+e.getMessage()+")", "Error de conversión",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 2. Realizo la conversión a pulgads
        Double pulgadas = centDouble / UNA_PULGADA;
        // 3. Mostrar el resultado en el Textfield de pulgas
        pulgTextField.setText(String.format("%.2f", pulgadas));
        //pulgTextField.setText(String.format(Locale.FRANCE , "%.2f", pulgadas));
    }

    private void centTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centTextFieldKeyPressed
        //System.out.println("Presionó una tecla");
        if (evt.getKeyChar()==KeyEvent.VK_ENTER) {
            convertirAPulgadas();
        }
    }//GEN-LAST:event_centTextFieldKeyPressed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCentimetrosButton;
    private javax.swing.JButton aPulgadasButton;
    private javax.swing.JTextField centTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pulgTextField;
    // End of variables declaration//GEN-END:variables
}
